#import pandas and numpy as pd and np respectively
import pandas as pd
import numpy as np
#load 5 datasets in pandas dataframe
df1 = pd.read_csv('2015 - 2015.csv')
df2 = pd.read_csv('2016 - 2016.csv')
df3 = pd.read_csv('2017 - 2017.csv')
df4 = pd.read_csv('2018 - 2018.csv')
df5 = pd.read_csv('2019 - 2019.csv') 

#Retrieve the list of countries in 2015 that have Health (LifeExpectancy) value between 0.5-1.
df1[(df1['Health (Life Expectancy)'] >= 0.5) & (df1['Health (Life Expectancy)'] <= 1)]['Country']

#Retrieve the top 10 countries with highest Happiness Score for the year 2016.
df2.sort_values(by='Happiness Score', ascending=False).head(10)['Country']

#Display the mean Happiness Score of the countries grouped by the Region for any year.
df1.groupby('Region')['Happiness Score'].mean()

#Identify if there are any outliers in your datasets (for all datasets 2015-2019)
df1.boxplot(column='Happiness Score')
df2.boxplot(column='Happiness Score')
df3.boxplot(column='Happiness Score')
df4.boxplot(column='Happiness Score')
df5.boxplot(column='Happiness Score')

#Analyze if there is any relationship between the Happiness Score and Economy (GDP per Capita) of the country for any year.
df1.plot.scatter(x='Happiness Score', y='Economy (GDP per Capita)')
df2.plot.scatter(x='Happiness Score', y='Economy (GDP per Capita)')
df3.plot.scatter(x='Happiness Score', y='Economy (GDP per Capita)')
df4.plot.scatter(x='Happiness Score', y='Economy (GDP per Capita)')
df5.plot.scatter(x='Happiness Score', y='Economy (GDP per Capita)')

#Combine the datasets from 2015-2019 to construct 1 dataframe that contains the following columns. Country, Region, Year (coming from the respective dataset) and Happiness Score for each year as a new column.
df1['Year'] = 2015
df2['Year'] = 2016
df3['Year'] = 2017
df4['Year'] = 2018
df5['Year'] = 2019
df1['Region'] = df1['Region'].str.strip()
df2['Region'] = df2['Region'].str.strip()
df3['Region'] = df3['Region'].str.strip()
df4['Region'] = df4['Region'].str.strip()
df5['Region'] = df5['Region'].str.strip()
df1['Country'] = df1['Country'].str.strip()
df2['Country'] = df2['Country'].str.strip()
df3['Country'] = df3['Country'].str.strip()
df4['Country'] = df4['Country'].str.strip()
df5['Country'] = df5['Country'].str.strip()
df1['Country'] = df1['Country'].str.replace(' ', '')
df2['Country'] = df2['Country'].str.replace(' ', '')
df3['Country'] = df3['Country'].str.replace(' ', '')
df4['Country'] = df4['Country'].str.replace(' ', '')
df5['Country'] = df5['Country'].str.replace(' ', '')
df1['Country'] = df1['Country'].str.replace('(', '')
df2['Country'] = df2['Country'].str.replace('(', '')
df3['Country'] = df3['Country'].str.replace('(', '')
df4['Country'] = df4['Country'].str.replace('(', '')
df5['Country'] = df5['Country'].str.replace('(', '')
df1['Country'] = df1['Country'].str.replace(')', '')
df2['Country'] = df2['Country'].str.replace(')', '')
df3['Country'] = df3['Country'].str.replace(')', '')
df4['Country'] = df4['Country'].str.replace(')', '')
df5['Country'] = df5['Country'].str.replace(')', '')
df1['Country'] = df1['Country'].str.replace('.', '')
df2['Country'] = df2['Country'].str.replace('.', '')
df3['Country'] = df3['Country'].str.replace('.', '')
df4['Country'] = df4['Country'].str.replace('.', '')
df5['Country'] = df5['Country'].str.replace('.', '')
df1['Country'] = df1['Country'].str.replace(',', '')
df2['Country'] = df2['Country'].str.replace(',', '')
df3['Country'] = df3['Country'].str.replace(',', '')
df4['Country'] = df4['Country'].str.replace(',', '')
df5['Country'] = df5['Country'].str.replace(',', '')
df1['Country'] = df1['Country'].str.replace("'", '')
df2['Country'] = df2['Country'].str.replace("'", '')
df3['Country'] = df3['Country'].str.replace("'", '')
df4['Country'] = df4['Country'].str.replace("'", '')
df5['Country'] = df5['Country'].str.replace("'", '')
df1['Country'] = df1['Country'].str.replace("-", '')
df2['Country'] = df2['Country'].str.replace("-", '')
df3['Country'] = df3['Country'].str.replace("-", '')
df4['Country'] = df4['Country'].str.replace("-", '')
df5['Country'] = df5['Country'].str.replace("-", '')
df1['Country'] = df1['Country'].str.replace("/", '')
df2['Country'] = df2['Country'].str.replace("/", '')
df3['Country'] = df3['Country'].str.replace("/", '')
df4['Country'] = df4['Country'].str.replace("/", '')
df5['Country'] = df5['Country'].str.replace("/", '')
df1['Country'] = df1['Country'].str.replace("&", '')
df2['Country'] = df2['Country'].str.replace("&", '')
df3['Country'] = df3['Country'].str.replace("&", '')
df4['Country'] = df4['Country'].str.replace("&", '')
df5['Country'] = df5['Country'].str.replace("&", '')
df1['Country'] = df1['Country'].str.replace("?", '')
df2['Country'] = df2['Country'].str.replace("?", '')
df3['Country'] = df3['Country'].str.replace("?", '')
df4['Country'] = df4['Country'].str.replace("?", '')
df5['Country'] = df5['Country'].str.replace("?", '')
df1['Country'] = df1['Country'].str.replace("!", '')
df2['Country'] = df2['Country'].str.replace("!", '')
df3['Country'] = df3['Country'].str.replace("!", '')
df4['Country'] = df4['Country'].str.replace("!", '')
df5['Country'] = df5['Country'].str.replace("!", '')
df1['Country'] = df1['Country'].str.replace(":", '')
df2['Country'] = df2['Country'].str.replace(":", '')
df3['Country'] = df3['Country'].str.replace(":", '')
df4['Country'] = df4['Country'].str.replace(":", '')
df5['Country'] = df5['Country'].str.replace(":", '')
df1['Country'] = df1['Country'].str.replace(";", '')
df2['Country'] = df2['Country'].str.replace(";", '')
df3['Country'] = df3['Country'].str.replace(";", '')
df4['Country'] = df4['Country'].str.replace(";", '')
df5['Country'] = df5['Country'].str.replace(";", '')
df1['Country'] = df1['Country'].str.replace("=", '')
df2['Country'] = df2['Country'].str.replace("=", '')
df3['Country'] = df3['Country'].str.replace("=", '')
df4['Country'] = df4['Country'].str.replace("=", '')
df5['Country'] = df5['Country'].str.replace("=", '')
df1['Country'] = df1['Country'].str.replace("+", '')
df2['Country'] = df2['Country'].str.replace("+", '')
df3['Country'] = df3['Country'].str.replace("+", '')
df4['Country'] = df4['Country'].str.replace("+", '')
df5['Country'] = df5['Country'].str.replace("+", '')
df1['Country'] = df1['Country'].str.replace("*", '')
df2['Country'] = df2['Country'].str.replace("*", '')
df3['Country'] = df3['Country'].str.replace("*", '')
df4['Country'] = df4['Country'].str.replace("*", '')
df5['Country'] = df5['Country'].str.replace("*", '')
df1['Country'] = df1['Country'].str.replace("$", '')
df2['Country'] = df2['Country'].str.replace("$", '')
df3['Country'] = df3['Country'].str.replace("$", '')
df4['Country'] = df4['Country'].str.replace("$", '')
df5['Country'] = df5['Country'].str.replace("$", '')
df1['Country'] = df1['Country'].str.replace("#", '')
df2['Country'] = df2['Country'].str.replace("#", '')
df3['Country'] = df3['Country'].str.replace("#", '')
df4['Country'] = df4['Country'].str.replace("#", '')
df5['Country'] = df5['Country'].str.replace("#", '')
df1['Country'] = df1['Country'].str.replace("@", '')
df2['Country'] = df2['Country'].str.replace("@", '')
df3['Country'] = df3['Country'].str.replace("@", '')
df4['Country'] = df4['Country'].str.replace("@", '')
df5['Country'] = df5['Country'].str.replace("@", '')
df1['Country'] = df1['Country'].str.replace("_", '')
df2['Country'] = df2['Country'].str.replace("_", '')
df3['Country'] = df3['Country'].str.replace("_", '')
df4['Country'] = df4['Country'].str.replace("_", '')
df5['Country'] = df5['Country'].str.replace("_", '')

#For any 2 countries of your choice draw a line chart (x-axis contains the years from the dataframe constructed in part g and y-axis contains the Happiness Score values for the respective years). Identify the trend. 
df1[df1['Country'] == 'India'].plot.line(x='Year', y='Happiness Score')
df1[df1['Country'] == 'UnitedStates'].plot.line(x='Year', y='Happiness Score')

#For the year 2015, identify the regions that have an Economy (GDP per Capita) value less than 0.5.
df1[df1['Economy (GDP per Capita)'] < 0.5]['Region']

#Identify which 2 variables have the highest correlations across all the countries for the years 2015 and 2016.
df1.corr()
df2.corr()

